### ISSUE TITLE
Concatenation failed, error

### ISSUE THREAD

**Issue by markmenezesmm** [parallelencode/PyParallelEncode#1]
hi, getting this error plz help!!

Error in encoding loop unsupported operand type(s) for +: 'NoneType' and 'int'
At line 140
.temp/concat: Invalid data found when processing input

Concatenation failed, error
At line: 25
Error:
Finished: 3.5s

this is the code im running:

import shlex
from pathlib import Path
from parallelencode import run
params = {
	"input": Path(r"D:\my docs\test\ashtavakra coming soon.mp4"), 
	"ffmpeg": shlex.split("-b:v libx264 -crf")
	}
run(params)

**Comment by natis1** [comment]
"-b:v libx264 -crf" is not a valid ffmpeg command because ffmpeg is expecting an actual crf value to be specified. eg: "-b:v libx264 -crf 20"

But this is still NOT what you want. if you want to encode in x264 you need "encoder" : "x264", "video_params" : shlex.split("--crf X")

It also requires vapoursynth and lsmash to be installed unless you set "chunk_method" : "segment"
